version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./devops/docker/react/Dockerfile
    image: frontend:latest
    command: bash -c "vite --host 0.0.0.0 --port 5000"
    env_file:
      - .env
    ports:
      - 5000:5000